### PR TITLE
Add documentation on timestamp resolution limitations on HFS+.

### PR DESCRIPTION
**Pull request by jessekempf**

### CODE REVIEW

**Comment by glguy** [comment]
I think it's less important what HFS+ has one second resolution and more important that people know that this API isn't going to increase the resolution beyond the source data, which is the filesystem. Every filesystem has its own constraints on timestamp resolution. It's possible that having a table of all the resolutions is a good idea, but I'm not sure that this is the right place for that. Additionally the resolution varies by metadata type. For example on FAT32 (according to wikipedia) we have:

```
2 seconds for last modified time,
10 ms for creation time,
1 day for access date,
2 seconds for deletion time
```

**Comment by ndmitchell** [comment]
@glguy I think it's important people know it's file system dependent. But in practice, on Linux it will usually be high resolution and on Mac it will usually be low resolution. That seems worth knowing to someone reading the API who isn't necessarily an expert in other platform specific differences.

**Comment by jessekempf** [comment]
That's a fair point; I think on #66 what tripped both me and @ndmitchell up was that HFS+ is frequently used for `~` on a popular Unix -- I wouldn't have been surprised were I mounting a FAT32 volume, but I was by OS X's behavior, and it seemed to me plausible that conditional compilation was failing somewhere, somehow (obviously not now, but at the time...). I'm new to Haskell, but not new to autoconf failing in bizarre ways.

So on the one hand, we've got `unix` as a wrapper library around `stat(2)`, `fstat(2)`, `lstat(2)`, etc.; and on the other hand we've got `System.Posix.Files` as the Haskell-y way of interacting with files on Unix -- I think seen from the second perspective keeping a table of resolutions, or at least a reference to a freely available one, is more reasonable than if one looks from the first perspective. Am I off base?

**Comment by ndmitchell** [comment]
I'd go with "Note that the time will only be as precise as the underlying filesystem provides (e.g. on HFS+ Mac OS volumes it will be rounded to the nearest second)".

**Comment by emilypi** [comment]
@jessekempf what's the status of this PR? Is it still in flight (or relevant?)

**Comment by emilypi** [comment]
I'm informed by @jessekempf that it is no longer relevant and he will not be continuing the PR.

**Review by emilypi — APPROVED** [review]
It's useful as is, and we can iterate on these changes.

**Pull request merged**
