### PR TITLE
JS: add support for utimes/lutimes/futimes

### PR DESCRIPTION
**Pull request by hsyl20**
In particular, add support for `touchFd` required here: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9237

Cc @bgamari

### CODE REVIEW

**Comment by hasufell** [comment]
How can we test this in CI?

**Comment by hsyl20** [comment]
You need to build GHC with the JS backend enabled. Apparently CI is using ghcup so it would be good to fix https://github.com/haskell/ghcup-hs/issues/838 first

**Comment by hsyl20** [comment]
> it's fine to add a custom CI job, which manually grabs GHC JS from elsewhere, without ghcup, if it's easier. But I'm reluctant to merge without one.

We're in the process of fixing GHCup to build cross-compilers. Moritz, however, suggested that we use the haskell.nix infrastructure to avoid the build times. I'll try this.

**Comment by hasufell** [comment]
> Moritz, however, suggested that we use the haskell.nix infrastructure to avoid the build times. I'll try this.

I personally don't want to maintain nix code in CI.

GHCup should be fixed to be able to install cross toolchain from bindist as well.

**Comment by hsyl20** [comment]
> I personally don't want to maintain nix code in CI.

Nix would only be used to provide the environment with the appropriate ghc (`nix shell some_url`). Does that count as nix code? :)

> GHCup should be fixed to be able to install cross toolchain from bindist as well.

Sadly upstream doesn't provide JS bindists. Does ghcup already provide custom bindists (and where are they hosted)?

**Comment by hasufell** [comment]
> Nix would only be used to provide the environment with the appropriate ghc (nix shell some_url). Does that count as nix code? :)

Yes, my experience with nix has been rather negative and I want to avoid pinging other people whenever there's a problem with it (and IME, there are a lot).

> Sadly upstream doesn't provide JS bindists.

We can just build our own.

**Comment by bgamari** [comment]
I have incorporated this change into [ghc!9237](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9237)

**Comment by hasufell** [comment]
ghcup is very close to being able to install ghc JS cross from bindist. I already built one: https://downloads.haskell.org/~ghcup/unofficial-bindists/ghc/javascript-unknown-ghcjs-9.6.2/

It'll require another ghcup release first. Then we'll maintain a separate ghcup metadata for JS.

**Comment by hsyl20** [comment]
I've opened https://github.com/haskell/unix/pull/290 to make the testsuite runnable with GHC head+[!10900](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10900) built with the JS backend. I just have to rebase and to add a test for this PR.

CI will be more difficult because we need to use GHC 9.8 at least. But releasing 9.8 might be blocked on this...

**Comment by hasufell** [comment]
Can't we just build a bindist from the current 9.8 branch? 

I already have ghcup CI that tests `ghcup compile ghc` against JS cross: https://github.com/haskell/ghcup-hs/actions/runs/5593656559

I don't think CI is prerequisite to get this merged, but it needs to remain a TODO list, so that we don't regress.

**Comment by hsyl20** [comment]
> Can't we just build a bindist from the current 9.8 branch?

After https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10900 is backported, we can.

> I don't think CI is prerequisite to get this merged, but it needs to remain a TODO list, so that we don't regress.

I've opened https://github.com/haskell/unix/issues/291 to track this.

**Comment by hsyl20** [comment]
I'm working on a test for this PR but I need https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10909 to fix `createFile` and https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10912 to fix `getFileStatus`...

**Comment by hsyl20** [comment]
@Bodigrim I'm on vacation this week but next week sure. I have a wip test but it isn't complete yet. There is also a test for touchFd in the ghc MR.

**Comment by hsyl20** [comment]
I've rebased. Test is stil wip and depends on (at least) https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10909 (currently being merged).

**Review by hasufell — APPROVED** [review]

**Review by Bodigrim — APPROVED** [review]

**Pull request merged**
