### PR TITLE
CI: replace centos:7 container by redhat/ubi9:latest

### PR DESCRIPTION
**Pull request by andreasabel**
Github disabled workflow `ci.yml` because its job `centos7` perpetually failed (Centos EOL).
This replaces the `centos:7` image by `redhat/ubi9:latest`.

SQUASH this PR upon merge.

### CODE REVIEW

**Comment by andreasabel** [comment]
[Somewhere](https://pythonspeed.com/articles/centos-8-is-dead/) it has been said that `redhat/ubi9` would be a replacement for `centos`.  It seems to work with minimal changes (dropping the obsolote `ncurses-compat-libs`).

**Review by Bodigrim — APPROVED** [review]

**Comment by Bodigrim** [comment]
Thanks!

**Comment by Bodigrim** [comment]
Arrrgh, I forgot to squash, will `push --force` in a moment.

**Comment by Bodigrim** [comment]
Apparently even my access level is not enough to `push --force`, I think a few repos were branch-protected by GitHub support a few years ago. Let's leave it as a monument to my inability to read.

**Comment by andreasabel** [comment]
Ok, no worries.  Been there, done that. :-D

Thanks!

**Comment by andreasabel** [comment]
I wish github would have a special label like "squash me" that one would have to remove first if one wanted to merge other than squash...  In the Agda repo, I created the "pr: squash me" label, but it is easy to overlook, does not have the magic I want it to have...

**Pull request merged**
