### PR TITLE
PosixString.hsc: expose Fd

### PR DESCRIPTION
**Pull request by domenkozar**

### CODE REVIEW

**Comment by domenkozar** [comment]
Quite a few of functions have `Fd` in their type signature, so now I need to import it from `System.IO` if I want to use them.

The way I see it, it already exposes the API on the `Fd` so it just makes it convenient to have it as one import.

The same goes for `SeekMode`.

**Comment by hasufell** [comment]
I don't have a strong opinion, but it should be consistent.

**Comment by hasufell** [comment]
ping

**Comment by hasufell** [comment]
Is there any interest in pursuing this further?

**Pull request closed without merging**
