### PR TITLE
Drop GHC < 8.2

### PR DESCRIPTION
**Pull request by Bodigrim**
As discussed in #164.

### CODE REVIEW

**Review by chessai — APPROVED** [review]

**Comment by chessai** [comment]
LGTM

**Comment by vdukhovni** [comment]
Looking at the resulting files, I still find a few `#if` conditionals on outdated GHC versions:
```
System/Posix/Signals.hsc:#if defined(darwin_HOST_OS) && __GLASGOW_HASKELL__ < 706
System/Posix/Terminal.hsc:# if __GLASGOW_HASKELL__ < 800
System/Posix/Terminal.hsc:# if __GLASGOW_HASKELL__ < 800
System/Posix/Terminal/ByteString.hsc:# if __GLASGOW_HASKELL__ < 800
System/Posix/Terminal/ByteString.hsc:# if __GLASGOW_HASKELL__ < 800
cbits/HsUnix.c:#if HAVE_PTSNAME && (__GLASGOW_HASKELL__ < 800)
```
Perhaps tidy these up also?

**Review by vdukhovni — APPROVED** [review]
Looks good now.

**Review by hs-viktor — APPROVED** [review]

**Comment by hs-viktor** [comment]
FWIW, I'm inclined to just push "Rebase and merge" without waiting for Emily, but I'm not doing it, because we haven't established proper protocol for this, so I don't know whether that'd be OK, or bad karma.  Which is it?

**Comment by chessai** [comment]
You and Bodigrim can proceed with full autonomy. You do not need to wait on
Emily or myself. We may chime in, but you are the maintainers.

**Pull request merged**
