### PR TITLE
Expose DirStream and friends, fixes #25

### LINKED ISSUE #25: export System.Posix.Directory.Common
Without `DirStream`, if you wish to do a deep traversal of a directory structure, it's necessary to stat everything in order to determine if it's a sub-directory (and needs to be descended into) or a regular file.  This imposes a significant performance penalty (see https://github.com/JohnLato/posix-paths for benchmarks).

I don't think there's any reason this module can't be exported in its entirety.

### PR DESCRIPTION
**Pull request by hasufell**
@JohnLato

### CODE REVIEW

**Comment by Bodigrim** [comment]
The prior art suggests `*.Internals`, not `*.Internal`.
The issues looks like it would be sufficient to export data types only. In this case it could be `*.Types`.

**Comment by hs-viktor** [comment]
> The prior art suggests `*.Internals`, not `*.Internal`.
> The issues looks like it would be sufficient to export data types only. In this case it could be `*.Types`.

I don't have a horse in this race, there are plenty of packages that export `.Internal` (e.g. `bytestring`).  No objections provided the user knows they're dabbling in interfaces outside the stability contract.

**Comment by Bodigrim** [comment]
I meant "prior art" in this very same package, [`System.Posix.Process.Internals`](https://hackage.haskell.org/package/unix-2.7.2.2/docs/System-Posix-Process-Internals.html).

**Comment by hasufell** [comment]
Done

**Review by Bodigrim — APPROVED** [review]

**Review by hs-viktor — APPROVED** [review]

**Pull request merged**
