### PR TITLE
Rebase of #21, original author moved on

### PR DESCRIPTION
**Pull request by hs-viktor**

### CODE REVIEW

**Comment by hs-viktor** [comment]
See PR #21 for original PR history.  Not yet ready.

**Comment by hs-viktor** [comment]
FreeBSD documentation for `setitimer` says:
```
STANDARDS
     The getitimer() and setitimer() functions conform to IEEE Std 1003.1-2001
     (“POSIX.1”).  The later IEEE Std 1003.1-2008 (“POSIX.1”) revision however
     marked both functions as obsolescent, recommending the use of
     timer_gettime(2) and timer_settime(2) instead.
```
So it seems we've gone from deprecating `ualarm(3)` to deprecating `setitimer(2)`, and requiring `timer_create(2)` and `timer_settime(2)`?
It sure looks POSIX also gets to break backwards compatibility...

**Comment by hs-viktor** [comment]
I'm inclined to drop this PR.  The `getitimer` and `setitimer` functions are obsolete per POSIX, and also have poor semantics in multi-threaded programs, since the `SIGALRM` delivered on timer expiration may be delivered to a thread that is not expecting it...

**Comment by Bodigrim** [comment]
@hs-viktor whatever works best for you, I don't mind to close.

**Comment by hs-viktor** [comment]
I've polished the PR into a reasonably working state, but will close it unmerged.  If someone wants to revive it later, they can start from here...

**Pull request closed without merging**
