### PR TITLE
Fix building and testing with the JS backend

### PR DESCRIPTION
**Pull request by hsyl20**
Note that most tests have been disabled because they don't pass due to missing C function support (e.g. pipe). But it's a good basis to start adding tests for supported things (e.g. touchFd, cf #285).

This requires a recent version of GHC that provides `getMonotonicTimeNSec`. See
https://gitlab.haskell.org/ghc/ghc/-/issues/23687 and https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10900.

### CODE REVIEW

**Comment by hsyl20** [comment]
For some reason, Fedora mirror site is 404

**Comment by bgamari** [comment]
Thanks for doing this, @hsyl20 !

**Review by bgamari — APPROVED** [review]

**Comment by hsyl20** [comment]
Yes otherwise the platform isn't recognized by the configure script.

**Comment by hsyl20** [comment]
(we overwrite these files when we build the package in the ghc tree)

**Review by hasufell — APPROVED** [review]

**Pull request merged**
