### PR TITLE
Add support for more OpenFileFlags and slightly refactor 'openFd'

### LINKED ISSUE #57: Missing O_NOFOLLOW
This is really annoying. I don't even understand why this library attempts to pre-select which flags I can pass in or not. That's not how a low-level library should be designed.

Since this library is about POSIX stuff, you should simply allow **all** POSIX flags, see http://www.unix.com/man-page/posix/3p/open/

> O_NOFOLLOW    If path names a symbolic link, fail and set errno to [ELOOP].

### LINKED ISSUE #58: "exclusive = True" may lead to undefined behavior
It's not very well documented, because `O_CREAT` is not passed like the other flags via `OpenFileFlags`, but implicitly via `Maybe FileMode`.

The [manpage](http://www.unix.com/man-page/posix/3p/open/) says that
> If O_EXCL is set and O_CREAT is not set, the result is undefined.

This library should either make the correspondence of those input arguments clear or make it impossible to use the combination. The following would already be quite an improvement:
```hs
-- |Correspond to some of the int flags from C's fcntl.h.
data OpenFileFlags =
 OpenFileFlags {
    append    :: Bool,           -- ^ O_APPEND
    exclusive :: Bool,           -- ^ O_EXCL, result is undefined if O_CREAT is False
    noctty    :: Bool,           -- ^ O_NOCTTY
    nonBlock  :: Bool,           -- ^ O_NONBLOCK
    trunc     :: Bool,           -- ^ O_TRUNC
    creat     :: Maybe FileMode  -- ^ O_CREAT 
 }
```
And then remove the extraneous `Maybe FileMode` arguments from `open_`.

### PR DESCRIPTION
**Pull request by hasufell**
Fixes #57
Fixes #58
Wrt #6 (only partly fixed)

### CODE REVIEW

**Comment by hasufell** [comment]
Another way could be like the `posix-paths` module does:
https://github.com/JohnLato/posix-paths/blob/master/src/System/Posix/Directory/Foreign.hsc

which then generates those Flags conveniently from `Foreign.hsc` into [Foreign.hs](https://gist.github.com/hasufell/51ffa3492b30e64a859bb83ceadb118a)... this also allows for platform-specific ifdefs.

The `_open` function then would look something like this:
```hs
open_  :: CString
       -> OpenMode
       -> [Flags]
       -> Maybe FileMode
       -> IO Fd
open_ str how optional_flags maybe_mode = do
    fd <- c_open str all_flags mode_w
    return (Fd fd)
  where
    all_flags  = unionFlags $ optional_flags ++ [open_mode] ++ creat

    (creat, mode_w) = case maybe_mode of
                        Nothing -> ([],0)
                        Just x  -> ([oCreat], x)

    open_mode = case how of
                   ReadOnly  -> oRdonly
                   WriteOnly -> oWronly
                   ReadWrite -> oRdwr
```

**Comment by hasufell** [comment]
seems there is zero interest?

**Comment by cartazio** [comment]
Busy time of year for many !

Unrelatedly: for our posix apis should we be using closed sums or slowly
moving over to pattern synonyms of the bit masks / flags?

**Comment by erikd** [comment]
@cartazio I'd prefer closed sums for now.

As for the code, I'm on the fence. Its going to break some stuff. Its a matter of whether its worth it. I'd be curious to see what @hvr thinks.

**Comment by Pastafarianist** [comment]
Can some of the developers look into this? Seems like a very useful PR.

**Comment by hasufell** [comment]
No time to maintain this. Developers are not responsive.

**Comment by cartazio** [comment]
@hvr you never gave feedback on this :(

**Comment by hvr** [comment]
Sorry, totally missed this one. So I see a couple of issues with the current approach; afaik the additional flags (O_NOFOLLOW, O_CLOEXEC, O_DIRECTORY and O_SYNC) were recent additions to the POSIX spec (they weren't yet part of the 2004 edition; they started appearing in the 2016 edition), and I'm not sure about how portable they are, so we may need to account for the possibility they aren't available everywhere.

And this poses the question how to deal when they're not available, and how to signal this to API consumers (c.f. #23) . Another issue is that the representation chosen requires us to make version major bumps whenever we add or remove fields from the `OpenFileFlags` type. I'd prefer a scheme which avoids that.

**Pull request closed without merging**
