### PR TITLE
System.Posix.Terminal: Add more terminal modes

### PR DESCRIPTION
**Pull request by bbarenblat**
Add ONLCR, OCRNL, ONOCR, ONLRET, OFILL, NLDLY, CRDLY, TABDLY, BSDLY, VTDLY, and FFDLY.

Closes: https://github.com/haskell/unix/issues/98

### CODE REVIEW

**Comment by glguy** [comment]
This seems like a good idea. Are all of these new CPP constants available on all the platforms we intend to support? In addition to building on the versions of things Travis uses I checked that it builds on current macOS. @hvr do you have any concerns about the more exotic platforms?

**Comment by hvr** [comment]
Those are all XSI features according to http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/termios.h.html

btw, `OFDEL` seems to be missing from the patch

**Comment by angerman** [comment]
I was able to successfully build armv7/android with this. iOS and aarch64/android, did not build due to some brokenness of my iOS and aarch64 toolchain apparently. I'll test once I've sorted that out.

However I believe iOS shouldn't be much of an issue (except from iOS sdks `termios.h`
```
/*
 * Input flags - software input processing
 */
#define IGNBRK          0x00000001      /* ignore BREAK condition */
#define BRKINT          0x00000002      /* map BREAK to SIGINTR */
#define IGNPAR          0x00000004      /* ignore (discard) parity errors */
#define PARMRK          0x00000008      /* mark parity and framing errors */
#define INPCK           0x00000010      /* enable checking of parity errors */
#define ISTRIP          0x00000020      /* strip 8th bit off chars */
#define INLCR           0x00000040      /* map NL into CR */
#define IGNCR           0x00000080      /* ignore CR */
#define ICRNL           0x00000100      /* map CR to NL (ala CRMOD) */
#define IXON            0x00000200      /* enable output flow control */
#define IXOFF           0x00000400      /* enable input flow control */
#define IXANY           0x00000800      /* any char will restart after stop */
#if !defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE)
#define IMAXBEL         0x00002000      /* ring bell on input queue full */
#define IUTF8           0x00004000      /* maintain state for UTF-8 VERASE */
#endif  /*(_POSIX_C_SOURCE && !_DARWIN_C_SOURCE) */

/*
 * Output flags - software output processing
 */
#define OPOST           0x00000001      /* enable following output processing */
#define ONLCR           0x00000002      /* map NL to CR-NL (ala CRMOD) */
#if !defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE)
#define OXTABS          0x00000004      /* expand tabs to spaces */
#define ONOEOT          0x00000008      /* discard EOT's (^D) on output) */
#endif  /*(_POSIX_C_SOURCE && !_DARWIN_C_SOURCE) */
/*
 * The following block of features is unimplemented.  Use of these flags in
 * programs will currently result in unexpected behaviour.
 *
 * - Begin unimplemented features
 */
#define OCRNL           0x00000010      /* map CR to NL on output */
#define ONOCR           0x00000020      /* no CR output at column 0 */
#define ONLRET          0x00000040      /* NL performs CR function */
#define OFILL           0x00000080      /* use fill characters for delay */
#define NLDLY           0x00000300      /* \n delay */
#define TABDLY          0x00000c04      /* horizontal tab delay */
#define CRDLY           0x00003000      /* \r delay */
#define FFDLY           0x00004000      /* form feed delay */
#define BSDLY           0x00008000      /* \b delay */
#define VTDLY           0x00010000      /* vertical tab delay */
#define OFDEL           0x00020000      /* fill is DEL, else NUL */
#if !defined(_SYS_IOCTL_COMPAT_H_) || __DARWIN_UNIX03
/*
 * These manifest constants have the same names as those in the header
 * <sys/ioctl_compat.h>, so you are not permitted to have both definitions
 * in scope simultaneously in the same compilation unit.  Nevertheless,
 * they are required to be in scope when _POSIX_C_SOURCE is requested;
 * this means that including the <sys/ioctl_compat.h> header before this
 * one when _POSIX_C_SOURCE is in scope will result in redefintions.  We
 * attempt to maintain these as the same values so as to avoid this being
 * an outright error in most compilers.
 */
#define         NL0     0x00000000
#define         NL1     0x00000100
#if !defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE)
#define         NL2     0x00000200
#define         NL3     0x00000300
#endif /* (_POSIX_C_SOURCE && !_DARWIN_C_SOURCE) */
#define         TAB0    0x00000000
#define         TAB1    0x00000400
#define         TAB2    0x00000800
/* not in sys/ioctl_compat.h, use OXTABS value */
#define         TAB3    0x00000004
#define         CR0     0x00000000
#define         CR1     0x00001000
#define         CR2     0x00002000
#define         CR3     0x00003000
#define         FF0     0x00000000
#define         FF1     0x00004000
#define         BS0     0x00000000
#define         BS1     0x00008000
#define         VT0     0x00000000
#define         VT1     0x00010000
#endif  /* !_SYS_IOCTL_COMPAT_H_ */
/*
 * + End unimplemented features
 */
```

Android has them in [`termbits.h`](https://chromium.googlesource.com/android_tools/+/20ee6d20/ndk/platforms/android-21/arch-x86/usr/include/asm-generic/termbits.h)

**Comment by glguy** [comment]
@hvr I believe the most recent commit addresses your concerns

**Comment by hvr** [comment]
Thanks everyone!

**Pull request merged**
