### PR TITLE
Bump upper bounds for base/bytestring/time

### LINKED ISSUE #150: Support time 1.10
[Changelog for time-1.10](http://hackage.haskell.org/package/time-1.10/changelog).

### PR DESCRIPTION
**Pull request by Bodigrim**
Allows `base-4.14`, `bytestring-0.11`, `time-1.{10,11}`. Comes with appropriate changes to the test matrix. 
Supersedes #152, #160, resolves #150, #159.

### CODE REVIEW

**Review by emilypi — APPROVED** [review]

**Comment by emilypi** [comment]
This supersedes #160. I'll go close that.

**Comment by emilypi** [comment]
@Bodigrim since @hvr is unresponsive as of late, and we an prove this doesn't break anything, I'm fine with merging.

**Comment by sjakobi** [comment]
Awesome! Thank you, @Bodigrim and @emilypi! :)

**Comment by mightybyte** [comment]
I've published a new hackage revision with these bumps.

**Pull request merged**
