### PR TITLE
Fix redundant pattern warning

### PR DESCRIPTION
**Pull request by sgraf812**
Needed for https://gitlab.haskell.org/ghc/ghc/merge_requests/2753

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Note that GHC's `unix` submodule currently tracks the `2.7` branch, not `master`. I'm sure what the procedure for getting patches into `2.7` is, however. (i.e., should a PR land in `master` and then be cherry-picked to `2.7` separately? Or should there be two separate PRs for each branch?)

**Comment by sgraf812** [comment]
Any news here? We'd like to get https://gitlab.haskell.org/ghc/ghc/merge_requests/2753 into HEAD before ICFP deadline next week...

**Comment by RyanGlScott** [comment]
Some discussion with @bgamari reveals that submitting another PR against the `2.7` branch with this commit cherry-picked is likely the best approach. In light of this, let's just go ahead and land this.

**Comment by RyanGlScott** [comment]
Eek, GitHub glitched out and somehow applied this commit _twice_ on `master`: once in 2f083f823622fb4380d709bafe1cef2759e23ff0 and another in f7b956cad4b2eb745d0278bf5029222d1c8dfc01 (which is just an empty commit). I guess there's no harm in having the extra empty commit, but do be wary of this when cherry-picking.

**Comment by bgamari** [comment]
Wow, bizarre.

**Pull request merged**
