### PR TITLE
WIP: Rebase of #24: Warn when functions are used on unsupported platforms.

### PR DESCRIPTION
**Pull request by hs-viktor**
Rebasing #24 

Some fixups expected.  Some functions can now just be required unconditionally, seven years have gone by...

### CODE REVIEW

**Comment by Bodigrim** [comment]
@hs-viktor could you please rebase?

**Comment by hs-viktor** [comment]
> @hs-viktor could you please rebase?

Done.

**Comment by Bodigrim** [comment]
Looks good to me. I suggest to merge as is; one can investigate whether some functions can be enabled unconditionally later.

**Comment by hs-viktor** [comment]
> Looks good to me. I suggest to merge as is; one can investigate whether some functions can be enabled unconditionally later.

Thanks.  Will do.

**Pull request merged**
