### PR TITLE
Fix segfault for `System.Posix.Env.ByteString.getEnvironment`

### LINKED ISSUE #274: `System.Posix.Env.ByteString.getEnvironment` segfaults on empty environment
Repro:
```haskell
import System.Posix.Env.ByteString

main :: IO ()
main = do
  clearEnv
  getEnvironment >>= print
```
The the technical issue is a missing null pointer check, but the real reason is that we have a lot of copy & paste code that has diverged.

### PR DESCRIPTION
**Pull request by sol**
(fixes #274)

### CODE REVIEW

**Comment by sol** [comment]
@hasufell apparently `master` is broken (see #276).

**Comment by hasufell** [comment]
I'm not sure master is broken. This could be a permission issue with your fork. There are cases where CI works on the main repo, but not when initiated via a fork.

**Comment by hasufell** [comment]
Ok, I reran the job on master and it also fails on NetBSD: https://cirrus-ci.com/build/4510365560602624

I believe @Bodigrim added it

**Comment by sol** [comment]
Regarding the other test failures:
```
unix-tests: printenv: executeFile: does not exist (No such file or directory)
```
It's not entirely clear to me why they don't fail on `master`.  Any ideas?

**Comment by sol** [comment]
Actually, I do know. I need to protect the environment for that test I added.

**Comment by sol** [comment]
Ok, CI (mostly) passes.  From my side this is good to go.

**Pull request merged**
